# Generated by Django 4.1.3 on 2022-11-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('statuses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='users.users')),
                ('performer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performer', to='users.users')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.statuses')),
                ('tag_id', models.ManyToManyField(to='tags.tags')),
            ],
        ),
    ]
