# Generated by Django 4.1.3 on 2022-11-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='performer_id',
            new_name='performer',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='status_id',
            new_name='status',
        ),
    ]
