# Generated by Django 4.1.3 on 2022-11-20 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_rename_creator_id_tasks_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='creator',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x103280c70> <django.db.models.query_utils.DeferredAttribute object at 0x103280d00>', on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
