# Generated by Django 4.1.3 on 2022-11-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_relationlink_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationlink',
            name='task',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks'),
        ),
    ]
