# Generated by Django 4.1.3 on 2022-11-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_relationlink_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tag_id',
            new_name='label',
        ),
    ]
