# Generated by Django 4.1.3 on 2022-11-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_labels_options_alter_labels_name'),
        ('tasks', '0006_alter_relationlink_options_alter_tasks_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='label',
        ),
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.RelationLink', to='labels.labels', verbose_name='Метки'),
        ),
    ]
