# Generated by Django 4.1.3 on 2022-11-20 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task_manager.users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_alter_tasks_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='creator',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
