# Generated by Django 4.1.3 on 2022-11-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_performer_tasks_executor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='label',
            new_name='labels',
        ),
    ]
