# Generated by Django 4.1.3 on 2022-11-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_label_tasks_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='status',
            new_name='statuses',
        ),
    ]
