# Generated by Django 4.1.3 on 2022-11-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_status_tasks_statuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='statuses',
            new_name='status',
        ),
    ]
